"""Add verification fields to Question model

Revision ID: c6bf334dca4e
Revises: 0662f0a8d4ea
Create Date: 2025-06-14 02:13:31.765299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bf334dca4e'
down_revision = '0662f0a8d4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verification_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('verification_metadata', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_metadata')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('verification_attempts')
        batch_op.drop_column('verification_confidence')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
